-- local neotest = require("neotest")
--
-- neotest.setup{
--   adapters = {
--     require("neotest-python")
--   }
-- }
--
-- vim.keymap.set("n", "<leader>tn", function() neotest.run.run() end)
-- vim.keymap.set("n", "<leader>tf", function() neotest.run.run(vim.fn.expand("%")) end)
-- vim.keymap.set("n", "<leader>tl", function() neotest.run.run_last() end)
-- vim.keymap.set("n", "<leader>ts", function() neotest.run.run({ suite = true}) end)
-- vim.keymap.set("n", "<leader>ta", function() neotest.run.attach() end)
-- vim.keymap.set("n", "<leader>to", function() neotest.output_panel.toggle() end)
