[window]
decorations = "None"
padding.x = 16
padding.y = 14

# Colors (Everforest Dark)
# https://github.com/alacritty/alacritty-theme/blob/master/themes/everforest_light.toml
# (with hard background contrast tweaks by me.)

# Default colors
[colors.primary]
background = '#272e33'
foreground = '#d3c6aa'

# Normal colors
[colors.normal]
black   = '#414b50'
red     = '#e67e80'
green   = '#a7c080'
yellow  = '#dbbc7f'
blue    = '#7fbbb3'
magenta = '#d699b6'
cyan    = '#83c092'
white   = '#d3c6aa'

# Bright colors
[colors.bright]
black   = '#414b50'
red     = '#e67e80'
green   = '#a7c080'
yellow  = '#dbbc7f'
blue    = '#7fbbb3'
magenta = '#d699b6'
cyan    = '#83c092'
white   = '#d3c6aa'

# Orange (used by Starship)
[[colors.indexed_colors]]
index = 208
color = '#e69875'
