#!/usr/bin/env bash

PYTHON_VERSIONS="3.12 3.11 3.10 3.9 3.8 3.7"

# requires https://github.com/pyenv/pyenv-update
pyenv update

installed_versions=

for version in $PYTHON_VERSIONS;
do
  # requires https://github.com/momo-lab/xxenv-latest
  pyenv install --skip-existing "$version:latest"
  installed_version=$(pyenv latest $version) 

  pyenv shell $installed_version
  PIP_REQUIRE_VIRTUALENV=false python -m pip install --upgrade \
    pip \
    pipx \
    setuptools \
    virtualenv \
    wheel
  pyenv shell -

  installed_versions="$installed_versions $installed_version"
done

pyenv global $installed_versions
