vim.api.nvim_set_option_value("shiftwidth", 4, {scope="local"})
vim.api.nvim_set_option_value("softtabstop", 4, {scope="local"})
vim.api.nvim_set_option_value("shiftwidth", 4, {scope="local"})
vim.api.nvim_set_option_value("colorcolumn", "72,80,88", {scope="local"})
vim.api.nvim_set_option_value("textwidth", 72, {scope="local"})
vim.api.nvim_set_option_value("formatoptions", "c,q", {scope="local"})
